[database]
driver="mysql" # MySQL, SQLite, etc. currently just support MySQL.
host="127.0.0.1"
port="3306"
user="root"
password=""
database="hitokoto"
charset= "utf8mb4"
category_table_name="hitokoto_categories"
sentences_table_name="hitokoto_sentence"

[core]
workdir="./sentences"
